[package]
name = "bagit-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.6.6", package = "gtk4", features= ["v4_10"] }

[dependencies.adw]
package = "libadwaita"
version = "0.3"
features = ["v1_3"]
